### PR TITLE
Fix withData propTypes warning

### PR DESCRIPTION
**Pull request by kennandavison**
Fixes:
screen shot 2018-03-12 at 2 05 36 am

If there's a cleaner syntax, I can update :D

### CODE REVIEW

**Comment by amaidah** [comment]
Bump! @gmaliandi

**Comment by mattclough1** [comment]
Bump! @gmaliandi

**Comment by m-torin** [comment]
Enforcing proptypes is great if you use them and not one of the other methods...

**Comment by adamsoffer** [comment]
@gmaliandi Any chance we can get this merged? 🙂

**Review by gmaliandi — APPROVED** [review]

**Comment by gmaliandi** [comment]
Oh damn sorry for taking so long to look at this, and also thanks @kennandavison :smile:

**Pull request merged**
